#!/bin/bash
# Exports Thunderbird account/SMTP settings, saved passwords, certificates,
# address book and message filters from this machine's active profile into
# ~/Downloads/tb-settings-export.zip, including an install.sh to import them
# on another Mac. Mail itself is not exported (IMAP re-downloads it).
#
# Usage: quit Thunderbird, then run:  bash export-tb-settings.sh
set -euo pipefail

OUT_DIR="$HOME/Downloads/tb-settings-export"
OUT_ZIP="$HOME/Downloads/tb-settings-export.zip"
SETTINGS_FILES=(prefs.js logins.json key4.db cert9.db abook.sqlite history.sqlite)

if pgrep -ix thunderbird >/dev/null 2>&1; then
  echo "ERROR: Thunderbird is running. Quit it completely (Cmd+Q), then re-run." >&2
  exit 1
fi

# Locate the active profile: prefer the [Install...] section, else first Path=
TB_DIR="$HOME/Library/Thunderbird"
INI="$TB_DIR/profiles.ini"
if [ ! -f "$INI" ]; then
  echo "ERROR: $INI not found — is Thunderbird installed on this machine?" >&2
  exit 1
fi
REL="$(awk -F= '/^\[Install/{f=1} f && /^Default=/{print $2; exit}' "$INI")"
[ -n "$REL" ] || REL="$(awk -F= '/^Path=/{print $2; exit}' "$INI")"
PROFILE="$TB_DIR/$REL"
if [ ! -f "$PROFILE/prefs.js" ]; then
  echo "ERROR: no prefs.js in detected profile: $PROFILE" >&2
  exit 1
fi
echo "Exporting from profile: $PROFILE"

rm -rf "$OUT_DIR" "$OUT_ZIP"
mkdir -p "$OUT_DIR/profile-files"

for f in "${SETTINGS_FILES[@]}"; do
  if [ -f "$PROFILE/$f" ]; then
    cp -p "$PROFILE/$f" "$OUT_DIR/profile-files/"
  else
    echo "note: $f not present, skipping"
  fi
done

# Message filters, preserving the ImapMail/<server>/ and Mail/<dir>/ layout
(cd "$PROFILE" && find ImapMail Mail -name msgFilterRules.dat 2>/dev/null || true) |
while IFS= read -r f; do
  mkdir -p "$OUT_DIR/profile-files/$(dirname "$f")"
  cp -p "$PROFILE/$f" "$OUT_DIR/profile-files/$f"
done

# Generate install.sh: the OLD_* header is expanded now, the body verbatim
{
  printf '%s\n' \
    '#!/bin/bash' \
    '# Imports the Thunderbird settings in profile-files/ into this machine'"'"'s' \
    '# active profile. Generated by export-tb-settings.sh.' \
    '#' \
    '# Usage: quit Thunderbird, then run:  bash install.sh' \
    'set -euo pipefail' \
    '' \
    "OLD_PROFILE=\"$PROFILE\"" \
    "OLD_HOME=\"$HOME\""
  cat <<'INSTALL_EOF'
SRC_DIR="$(cd "$(dirname "$0")/profile-files" && pwd)"

if pgrep -ix thunderbird >/dev/null 2>&1; then
  echo "ERROR: Thunderbird is running. Quit it completely (Cmd+Q), then re-run." >&2
  exit 1
fi

TB_DIR="$HOME/Library/Thunderbird"
INI="$TB_DIR/profiles.ini"
if [ ! -f "$INI" ]; then
  echo "ERROR: $INI not found. Launch Thunderbird once (skip account setup)," >&2
  echo "       quit it, then re-run this script." >&2
  exit 1
fi

# Prefer the profile pinned in the [Install...] section, else first Path= entry
REL="$(awk -F= '/^\[Install/{f=1} f && /^Default=/{print $2; exit}' "$INI")"
[ -n "$REL" ] || REL="$(awk -F= '/^Path=/{print $2; exit}' "$INI")"
PROFILE="$TB_DIR/$REL"
if [ ! -d "$PROFILE" ]; then
  echo "ERROR: profile directory not found: $PROFILE" >&2
  exit 1
fi
echo "Target profile: $PROFILE"

BACKUP="$PROFILE/backup-before-import-$(date +%Y%m%d-%H%M%S)"
mkdir -p "$BACKUP"
for f in prefs.js logins.json key4.db cert9.db abook.sqlite history.sqlite; do
  [ -f "$PROFILE/$f" ] && cp -p "$PROFILE/$f" "$BACKUP/"
done
echo "Backed up existing files to: $BACKUP"

for f in prefs.js logins.json key4.db cert9.db abook.sqlite history.sqlite; do
  [ -f "$SRC_DIR/$f" ] && cp -p "$SRC_DIR/$f" "$PROFILE/$f"
done

# WAL files from the old machine were not exported; remove any stale local
# ones so SQLite doesn't pair them with the imported databases
rm -f "$PROFILE"/abook.sqlite-wal "$PROFILE"/abook.sqlite-shm \
      "$PROFILE"/history.sqlite-wal "$PROFILE"/history.sqlite-shm

# Rewrite absolute paths from the old machine to this profile / home
perl -pi -e "s|\Q$OLD_PROFILE\E|$PROFILE|g; s|\Q$OLD_HOME\E|$HOME|g" "$PROFILE/prefs.js"

# Message filters: place them where prefs.js now expects the account dirs
(cd "$SRC_DIR" && find ImapMail Mail -name msgFilterRules.dat 2>/dev/null || true) |
while IFS= read -r f; do
  mkdir -p "$PROFILE/$(dirname "$f")"
  cp -p "$SRC_DIR/$f" "$PROFILE/$f"
done

echo
echo "Done. Start Thunderbird — accounts, SMTP servers, saved passwords,"
echo "address book and filters are in place; IMAP mail will re-download."
echo "If anything looks wrong, restore from: $BACKUP"
INSTALL_EOF
} > "$OUT_DIR/install.sh"
chmod +x "$OUT_DIR/install.sh"
bash -n "$OUT_DIR/install.sh"

(cd "$(dirname "$OUT_DIR")" && zip -rq "$OUT_ZIP" "$(basename "$OUT_DIR")")
echo
echo "Created: $OUT_ZIP"
echo "Transfer it to the other Mac, unzip, quit Thunderbird there, run install.sh."
